version: 2

references:
    pin-npm-version: &pin-npm-version
        run:
            name: Pin NPM to specified version
            command: sudo npm install -g npm@6.13.4

jobs:
    test:
        docker:
            - image: circleci/node:12.16.0

        steps:
            - *pin-npm-version
            - checkout

            - restore_cache:
                  keys:
                      - jscache-{{ checksum "package.json" }}
                      - jscache-

            - run: npm ci

            - save_cache:
                  paths:
                      - node_modules
                  key: jscache-{{ checksum "package.json" }}

            - run: npm run lint

    publish:
        docker:
            - image: circleci/node:12.16.0

        steps:
            - *pin-npm-version
            - checkout
            - add_ssh_keys:
                  fingerprints:
                      - 'd8:ba:31:e6:71:55:e2:a8:a8:9a:0e:d1:6a:01:27:92'

            - run:
                  name: Set branch environemnt variable
                  command: |
                      echo '(echo "$CIRCLE_TAG" | grep -Eq  ^.*-rc.*$) && export BRANCH=$(echo "$CIRCLE_TAG" | sed "s/^v//" | sed "s/-rc.*//") || export BRANCH="master"' >> $BASH_ENV
                      source $BASH_ENV
            - run: npm version --no-git-tag-version ${CIRCLE_TAG}
            - run: git add package.json package-lock.json
            - run: git commit -m "Automatic NPM version bump ${CIRCLE_TAG}"
            - run: git checkout -b temp
            - run: git push origin temp:$BRANCH
            - run: npm config set '//registry.npmjs.org/:_authToken' '${NPM_TOKEN}'
            - run: npm publish --access public

    publish-hot:
        docker:
            - image: circleci/node:12.16.0

        steps:
            - *pin-npm-version
            - checkout
            - run: npm version --no-git-tag-version ${CIRCLE_TAG}
            - run: npm config set '//registry.npmjs.org/:_authToken' '${NPM_TOKEN}'
            - run: npm publish --access public

workflows:
    version: 2
    test-and-publish:
        jobs:
            - test:
                  filters:
                      tags:
                          only: /.*/
            - publish:
                  context: npm-publish
                  requires:
                      - test
                  filters:
                      tags:
                          only: /^v[0-9]+(\.[0-9]+)*(-rc\.[0-9]*)*/
                      branches:
                          ignore: /.*/
            - publish-hot:
                  context: npm-publish
                  requires:
                      - test
                  filters:
                      tags:
                          only: /^v[0-9]+(\.[0-9]+)*-hot/
                      branches:
                          ignore: /.*/
